version: '3'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
    tty: true
    container_name: node
    hostname: node
    command: sh -c 'serve ./dist -l 3000'
    volumes:
      - ./src:/src
      - /src/node_modules
    ports:
      - '${NODE_PORT}:3000'

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

